# Setup laravel environment + ansible for deployment.

FROM jenkins/ssh-agent:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
	php8.4 \
	php-xml \
	php-mbstring \
	php-curl \
	php-sqlite3 \
	php-fileinfo \
	php-zip \
	npm \
	ansible \
	openssh-client \
	sshpass \
	rsync \
	curl \
	git \
	unzip \
	openssl \
	libssl-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php -r "if (hash_file('sha384', 'composer-setup.php') === 'c8b085408188070d5f52bcfe4ecfbee5f727afa458b2573b8eaaf77b3419b0bf2768dc67c86944da1544f06fa544fd47') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }" \
	&& php composer-setup.php \
	&& php -r "unlink('composer-setup.php');" \
	&& mv composer.phar /usr/local/bin/composer
