# Setup laravel environment

FROM jenkins/ssh-agent:latest
RUN apt update && apt install php8.4 -y
RUN apt install -y php-xml php-mbstring php-curl npm php-sqlite3
RUN apt install -y php-fileinfo php-zip
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'c8b085408188070d5f52bcfe4ecfbee5f727afa458b2573b8eaaf77b3419b0bf2768dc67c86944da1544f06fa544fd47') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

# Ansible 
RUN apt install -y ansible sshpass openssl libssl-dev
